backend:
  name: github
  repo: Arwen-store/Arwen
  branch: main
  base_url: https://decap-cmsa-oauth.vercel.app

# ğŸ“¸ Where images are saved
media_folder: "img"
public_folder: "/img"

collections:
  - name: "products"
    label: "Ø§Ù„Ù…Ù†ØªØ¬Ø§Øª"
    label_singular: "Ù…Ù†ØªØ¬ Ø¬Ø¯ÙŠØ¯"
    folder: "_products"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "product" }
      - { label: "Ø§Ù„Ø¹Ù†ÙˆØ§Ù†", name: "title", widget: "string" }

      - label: "Ø§Ù„Ø¹Ù„Ø§Ù…Ø© Ø§Ù„ØªØ¬Ø§Ø±ÙŠØ©"
        name: "brand"
        widget: "select"
        options:
          - "Laverne"
          - "Assaf"

      - label: "Ø§Ù„Ø¬Ù†Ø³"
        name: "gender"
        widget: "select"
        options:
          - "Men"
          - "Women"
          - "unisex"

      - { label: "Ø§Ù„ØµÙˆØ±Ø© Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©", name: "image", widget: "image" }

      - label: "Ù…Ø¹Ø±Ø¶ Ø§Ù„ØµÙˆØ±"
        name: "images"
        widget: "list"
        field: { label: "ØµÙˆØ±Ø©", name: "image", widget: "image" }

      - { label: "Ø§Ù„ÙˆØµÙ", name: "description", widget: "text" }

      - label: "Ø§Ù„Ø§Ø­Ø¬Ø§Ù… ÙˆØ§Ù„Ø£Ø³Ø¹Ø§Ø±"
        name: "sizes"
        widget: "list"
        field:
          label: "Ø§Ù„Ø­Ø¬Ù… Ùˆ Ø§Ù„Ø³Ø¹Ø±"
          name: "size_price"
          widget: "object"
          fields:
            - label: "Ø§Ù„Ø­Ø¬Ù…"
              name: "size"
              widget: "select"
              options:
                - "30ML"
                - "50ML"
                - "75ML"
                - "100ML"
                - "150ML"
                - "200ML"
              required: true
            - { label: "Ø§Ù„Ø³Ø¹Ø±", name: "price", widget: "number", value_type: "float", required: true }

      - label: "ØªØ§Ø±ÙŠØ® Ø§Ù„Ø¥Ø¶Ø§ÙØ©"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
        required: true


      - label: ""
        name: "spacer_after_date"
        widget: "markdown"
        default: "<br><br>"
        required: false







  - name: "dummy_section"
    label: "ğŸª„ Dummy Section"
    folder: "_dummy_section"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Useless Title", name: "useless_title", widget: "string", required: false }
      - { label: "Useless Text", name: "useless_text", widget: "text", required: false }
      - { label: "Completely Pointless Numbr", name: "useless_number", widget: "number", required: false }